"""Change answer column to ARRAY

Revision ID: f79525630eee
Revises: d70169e02a98
Create Date: 2024-07-06 14:16:45.001779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79525630eee'
down_revision: Union[str, None] = 'd70169e02a98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_question',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'question_id')
    )
    op.add_column('questions', sa.Column('is_correct', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_correct')
    op.drop_column('questions', 'is_correct')
    op.drop_table('category_question')
    # ### end Alembic commands ###
